version: "3.4"
services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ${CONFIG}/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
      
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ${CONFIG}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:openvpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${CONFIG}/deluge:/config # config files

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG}/bazarr:/config # config files
      - ${ROOT}/movies:/movies # movies folder, same as Radarr
      - ${ROOT}/tv:/tv # tv shows folder, same as Sonarr
    ports:
      - 6767:6767

  plex-server:
    container_name: plex-server
    image: linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - VERSION=docker
    volumes:
      - ${CONFIG}/plex/db:/config # plex database
      - ${CONFIG}/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/tv:/data/tvshows # tvshows library
      - ${ROOT}/movies:/data/movies # tvshows library

volumes:
  yacht:
