version: "3.4"
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/home-assistant:/config # config files
    privileged: true
    ports:
      - 8123:8123 # Home Assistant web UI

#  esphome:
#    container_name: esphome
#    image: ghcr.io/esphome/esphome:stable
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      - PUID=${PUID} # default user id, defined in .env
#      - PGID=${PGID} # default group id, defined in .env
#      - TZ=${TZ} # timezone, defined in .env
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ${CONFIG}/esphome:/config # config files
#    ports:
#      - 6052:6052 # ESPHome web UI