global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "airgradient-bedroom"
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets: ["airgradient-ip-address:9926"]
