- id: "1693097348663"
  alias: Decorations Turn On
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 00:30:00
  condition: []
  action:
    - type: turn_on
      device_id: cfbc24b448b9242a715a3e516259cea9
      entity_id: 31dc0b7b496f6151fb9b8aa9e6e8bb5a
      domain: switch
  mode: single
- id: "1693097555638"
  alias: Decorations Turn Off Weekdays
  description: ""
  trigger:
    - platform: time
      at: "22:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
  action:
    - type: turn_off
      device_id: cfbc24b448b9242a715a3e516259cea9
      entity_id: 31dc0b7b496f6151fb9b8aa9e6e8bb5a
      domain: switch
  mode: single
- id: "1693097682534"
  alias: Decorations Turn Off Weekends
  description: ""
  trigger:
    - platform: time
      at: "22:30:00"
  condition:
    - condition: time
      weekday:
        - fri
        - sat
  action:
    - type: turn_off
      device_id: cfbc24b448b9242a715a3e516259cea9
      entity_id: 31dc0b7b496f6151fb9b8aa9e6e8bb5a
      domain: switch
  mode: single
