# Loads default set of integrations. Do not remove.
default_config:

panel_iframe:
  esphome:
    title: "ESPHome"
    icon: mdi:chip
    url: http://192.168.31.63:6052

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
