# Airgradient Pro presoldered edition
# D1 mini v4.0.0 with usb c port
substitutions:
  devicename: <DEVICE_NAME>
  friendly_devicename: <FRIENDLY_DEVICE_NAME>
  web_server_port: <WEB_SERVER_PORT>

esphome:
  name: "${devicename}"
  friendly_name: "${friendly_devicename}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  # name_add_mac_suffix: true
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:

# See: https://community.home-assistant.io/t/esphome-flashing-over-wifi-does-not-work/357352
switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_devicename}"
    password: !secret ap_password

captive_portal:

i2c:
  sda: D2
  scl: D1

font:
  - file: "fonts/FreeSans-LrmZ.ttf"
    id: freeSans
    size: 12
  - file: "fonts/OpenSans-B9K8.ttf"
    id: openSans
    size: 12
  - file: "gfonts://Roboto"
    id: roboto
    size: 12

display:
  - platform: ssd1306_i2c
    id: oled
    address: 0x3c
    model: "SH1106 128x64"
    lambda: |-
      it.printf(0, 0, id(openSans), "PM: %.0f  CO2: %.0f", id(pm25).state, id(co2).state);
      it.printf(0, 20, id(openSans), "TVOC: %.0f  NOX: %.0f", id(voc).state, id(nox).state);
      it.printf(0, 40, id(openSans), "F: %.2f  H: %.0f%%", (id(temp).state * 1.8) + 32, id(humidity).state);

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_1
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_2

sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: Temperature
    humidity:
      id: humidity
      name: Humidity
    address: 0x44
    update_interval: 60s
  - platform: pmsx003
    # type can be PMSX003, PMS5003S, PMS5003T, PMS5003ST
    # https://esphome.io/components/sensor/pmsx003.html
    type: PMSX003
    uart_id: uart_1
    pm_1_0:
      id: pm10
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      id: pm25
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      id: pm100
      name: "Particulate Matter <10.0µm Concentration"
    update_interval: 60s
  # If you have a version of the PMS*003* sensor that supports formaldehyde, uncomment the below block
  #    formaldehyde:
  #      id: hcho
  #      name: "Formaldehyde (HCHO) concentration in µg per cubic meter"
  - platform: senseair
    uart_id: uart_2
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 60s
  - platform: sgp4x
    voc:
      id: voc
      name: "VOC Index"
    nox:
      id: nox
      name: "NOx Index"
    store_baseline: true
    update_interval: 60s
    compensation:
      temperature_source: temp
      humidity_source: humidity
# Provide a /metrics endpoint for Prometheus
#prometheus:
#web_server:
#  port: ${web_server_port}
#  version: 1
